name: Easy-itv DockerImage  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
 


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Golang
        run: |
          wget https://studygolang.com/dl/golang/go1.23.6.linux-amd64.tar.gz      
          sudo tar -C /usr/local -zxvf go1.23.6.linux-amd64.tar.gz
          go version
          go install mvdan.cc/garble@latest
          go mod tidy

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag easy-itv-daix:tmp
          docker save -o easy-itv-daix.tar easy-itv-daix:tmp

  
      - name: Generate release tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          touch release.txt
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> release.txt


      - name: Upload image.tar to release
        uses: softprops/action-gh-release@master
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(date +"%Y.%m.%d-%H%M")
          body_path: release.txt
          files: easy-itv-daix.tar
